--- #YAML:1.0
name:               Robotics-IRobot
version:            0.1
abstract:           provides interface to iRobot Roomba and Create robots
author:
    - Michael Ratliff <email@michaelratliff.com>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:  0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.55_02
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
